### ISSUE TITLE
How to go about stochastics for implementing `min/max_total_cumulated_flows`

### ISSUE THREAD

**Issue by mihlema** [Spine-project/SpineOpt.jl#418]
Trying to add cumulated bounds to SpineOpt, we have formulated the following constraint:
```
function add_constraint_total_cumulated_unit_flow!(m::Model, bound,sense,d)
    @fetch unit_flow = m.ext[:variables]
    m.ext[:constraints][bound.name] = Dict(
        (unit=ug, node= ng, stochastic_path = s,t=t ) => sense_constraint(
            m,
            + expr_sum(
                unit_flow[u, n, d, s, t] * duration(t)
                for (u, n, d, s, t) in unit_flow_indices(
                    m;
                    unit=ug,
                    node = ng,
                    direction=d,
                    stochastic_scenario=s);
                    init = 0
            ),
            sense,
            bound(unit = ug, node = ng)
        ) for (ug,ng,s) in constraint_total_cumulated_unit_flow_indices(m,bound,d)
    )
end
```
where bound `sense` can be `>=, <=, =` and bound is either `max, min`. The bound should be over the entire modeling horizon (*Note: There will be another constraint following for the annual cumulative bounds*). The tricky part here seems to be the stochastics - and what exactly we want to achieve.

As indicated above, the `constraint_total_cumulated_unit_flow_indices(m,bound,d)` does  return a tuple of `ug`,`ng` and stochastic_path `s`. The `bound` parameter itself, however doesn't have temporals nor stochastics. For the temporals, this is a logical, as we want to cumulate over the entire model horizon. For the stochastics, this might not be straightforward. There's two things to decide/discuss
## Do we want a scenario-dependent `bound`?
This is the first decision we need to look at. For example, is there a case where we want to have different max/min bounds for different investment cases? I think we might - or at least maybe we shouldn't exclude it ex-ante. In this case, our bound would have another index `stochastic_scenario = s`, where s would correspond to the investment scenario. So how to retrieve this stochastic scenario though? We could use the `unit_investment__stochastic_structure` relationship for this. But how would this then work in problems without an investment decision? 
## Should the `bound` be imposed for each scenario path separately?
As illustrated in the constraint above, we generate the constraint for each potential scenario path. However is this what we want/ the only option we want to provide? For example, we could also drop the stochastic_path from the indices function and constrain the expected value to the `bound` parameter, by multiplying each stochastic_path realization with it's `node_stochastic` weight (similar to objective function). I think the best way to go about it is to provide to separate constraints, one on the expected value and one for each realization - the user can choose which one is applicable for their use case.
@DillonJ @Tasqu @jkiviluo any comments?

**Comment by jkiviluo** [comment]
I think it's more important to impose the constraint on the individual stochastic paths. Constraining the expected value will let the model go overboard on some of the paths (as long as others compensate) and that may be a difficult assumption to justify. However, there may be use cases for the expected value that I don't see right now. I'm just thinking about the CO2 limits kind of stuff.

**Comment by DillonJ** [comment]
Couple of thoughts here...
 - Rather than having separate constraints to implement bounds over different time horizons, it feels this is a perfect case for a relationship with a temporal block - then the functionality becomes way more generic and, I would argue, way more useful?
  - Something I would like to do eventually is add the functionality to the user constraint to allow them to be cumulative. It's basically very similar to my suggestion above - you could create a `user_constraint__temporal_block` relationship and a RHS parameter defined on that relationship and then the LHS of the constraint is summed over all timeslices in the temporal block(s). The user constraint already provides for different senses also. This would greatly increase the utility and allow us to implement these cumulative bounds very easily. Whether or not we have a dedicated cumulative bound constraint though, I think this makes a lot of sense. 
  - We could also extend the `user_constraint` to have the option of applying cumulatively (with weights) across scenarios to implement your expected value option, but otherwise, RHS can be defined as a map to have a value for each scenario individually.

**Comment by mihlema** [comment]
Thanks a lot for the input. We did go with the individual stochastic paths now. But I'm also happy about the additional suggestions. We've merged the "basic" version now (with tests and docs), but will look into the advanced use cases now.
