### ISSUE TITLE
Simple investment trial

### ISSUE THREAD

**Issue by CyrilChambe** [Spine-project/SpineOpt.jl#470]
Hello,

I am currently having a hard time trying to make investment decisions using Spine.

I followed what is explained in the documentation here : https://spine-project.github.io/SpineOpt.jl/latest/advanced_concepts/investment_optimization/#Creating-an-Investment-Candidate-Unit-Example.
However, the optimization seems not to work since no unit is invested in, whereas there is no other mean of production. I looked for anything I could have done wrong but I really don't see where does the problem come from.

Could you please have a look and tell me what is wrong in the implementation I made ?

I attach the .json file of the input database I use.

Best regards,

Cyril

[VerySimpleInvestment.zip](https://github.com/Spine-project/SpineOpt.jl/files/8928594/VerySimpleInvestment.zip)

**Comment by mihlema** [comment]
Hi Cyril,
thanks for opening this issue and for providing an example database. The first thing I notice when looking into your db is that there is no `model__default_investment_stochastic_structure` relationship - or alternatively a `unit__investment_stochastic_strucutre` relationship. I think that might be causing the problem here. Let me know if that solves your problem, otherwise we will have a look again.

**Comment by CyrilChambe** [comment]
Hello, thank you for your answer, this indeed solved the problem I had !
